version: "3"

networks:
  proxy:
    external: true

services:
  blog:
    image: llitfkitfk/blog
    restart: always
    ports:
      - 1313:1313
    # networks:
    #   - proxy
    environment:
      VIRTUAL_HOST: blog.gokit.info
      VIRTUAL_PORT: 1313
      LETSENCRYPT_HOST: blog.gokit.info
      LETSENCRYPT_EMAIL: llitfkitfk@gmail.com
